server:
  port: 8761

spring:
  application:
    name: eureka-server
  config:
    import: "optional:configserver:http://${CONFIG_HOST:config-server}:8888"

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-server:8761/eureka/