spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
server:
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
